import { ChainId, MULTICALL_ADDRESS } from '@daoswapdex/daoswap-dex-sdk'
import MULTICALL_ABI from './abi.json'

const MULTICALL_NETWORKS: { [chainId in ChainId]: string } = {
  [ChainId.BSC_MAINNET]: '0x133BCed277e1c56D88317b49Df56135789c42711', // MULTICALL_ADDRESS[ChainId.BSC_MAINNET],
  [ChainId.BSC_TESTNET]: MULTICALL_ADDRESS[ChainId.BSC_TESTNET],
  [ChainId.HECO_MAINNET]: MULTICALL_ADDRESS[ChainId.HECO_MAINNET],
  [ChainId.HECO_TESTNET]: MULTICALL_ADDRESS[ChainId.HECO_TESTNET]
}

export { MULTICALL_ABI, MULTICALL_NETWORKS }
